import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Navbar } from '@/view/navbar'
import SideBar from './sideBar'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Gallery App',
  description: 'Generated by Danish ALi',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className=''>
      <head>
    
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
    
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff" />
        </head>
        
      <body className={inter.className}>
        <Navbar />
        <div className='flex bg-[#e6d7cc] min-h-screen '>
          <div className='lg:w-1/4'>
            <SideBar />
          </div>
          <div className='w-full'>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
